# Generated by Django 5.1.15 on 2026-07-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('ready_for_1c', 'Ready for 1C'), ('exported', 'Exported'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=32),
        ),
    ]
